/**
 * Push Google Ads Campaign Plan v4 to Google Ads API.
 * Run: npx tsx scripts/push-campaign-plan-v4.ts
 */
import { config } from "dotenv";
config({ path: ".env.local" });

import { pushCampaignToGoogleAds } from "../src/lib/marketing/google-ads-client";
import type { CampaignDesign } from "../src/lib/marketing/campaign-designer";

const GEO_TARGETS = [
  { name: "Patchogue, NY", criterionId: 1027227 },
  { name: "Bellport, NY", criterionId: 1027211 },
  { name: "East Patchogue, NY", criterionId: 1027212 },
  { name: "Medford, NY", criterionId: 1027213 },
  { name: "Mastic, NY", criterionId: 1027214 },
  { name: "Shirley, NY", criterionId: 1027215 },
  { name: "Center Moriches, NY", criterionId: 1027216 },
  { name: "East Moriches, NY", criterionId: 1027217 },
  { name: "Manorville, NY", criterionId: 1027218 },
  { name: "Riverhead, NY", criterionId: 1025006 },
  { name: "Hampton Bays, NY", criterionId: 1027219 },
  { name: "Southampton, NY", criterionId: 1025105 },
  { name: "Westhampton, NY", criterionId: 1027220 },
  { name: "East Hampton, NY", criterionId: 1025022 },
  { name: "Miller Place, NY", criterionId: 1027221 },
  { name: "Ridge, NY", criterionId: 1027222 },
  { name: "Wading River, NY", criterionId: 1027223 },
  { name: "Calverton, NY", criterionId: 1027224 },
  { name: "Mattituck, NY", criterionId: 1027225 },
  { name: "Coram, NY", criterionId: 1027226 },
];

const campaigns: CampaignDesign[] = [
  // ═══ Campaign 1: Topsoil & Soil (Tier 1) ═══
  {
    campaignName: "ELM - Topsoil & Soil - Spring 2026",
    dailyBudgetCents: 1800,
    biddingStrategy: "MAXIMIZE_CLICKS",
    geoTargets: GEO_TARGETS,
    landingPageUrl: "/buy/topsoil",
    adGroups: [
      {
        name: "Topsoil Delivery",
        keywords: [
          { text: "topsoil delivery near me", matchType: "EXACT" },
          { text: "buy topsoil in bulk", matchType: "EXACT" },
          { text: "topsoil delivery suffolk county", matchType: "EXACT" },
          { text: "screened topsoil for sale", matchType: "EXACT" },
          { text: "topsoil delivery cost", matchType: "EXACT" },
          { text: "topsoil delivery price", matchType: "EXACT" },
          { text: "topsoil delivery long island", matchType: "PHRASE" },
          { text: "bulk topsoil near me", matchType: "PHRASE" },
          { text: "topsoil per cubic yard", matchType: "PHRASE" },
          { text: "organic topsoil delivery", matchType: "PHRASE" },
          { text: "same day topsoil delivery", matchType: "PHRASE" },
          { text: "topsoil delivery near me", matchType: "PHRASE" },
          { text: "topsoil delivery patchogue", matchType: "PHRASE" },
          { text: "topsoil delivery riverhead", matchType: "PHRASE" },
          { text: "topsoil delivery hampton bays", matchType: "PHRASE" },
          { text: "topsoil supplier suffolk county", matchType: "BROAD" },
          { text: "topsoil yard near patchogue", matchType: "BROAD" },
          { text: "landscape supply near me", matchType: "BROAD" },
        ],
        negativeKeywords: ["potting soil", "potting mix", "garden center", "jobs", "hiring", "free", "diy", "how to make", "home depot", "lowes", "amazon", "walmart", "bagged", "craigslist"],
        ads: [
          {
            headlines: [
              "Eastern Landscape Supply",
              "Topsoil Delivered Tomorrow",
              "Topsoil From $24 Per Yard",
              "Skip the Store - Go Bulk",
              "Real Topsoil, Not Bagged",
              "Same-Day Topsoil Delivery",
              "Suffolk Topsoil Delivered",
              "Screened Topsoil In Stock",
              "Dumped Where You Need It",
              "Local Yard, Real Inventory",
              "No Bags - Bulk Saves Money",
              "Get Topsoil Delivered Today",
              "Fast Delivery From Our Yard",
              "Call Us Today",
              "Order Topsoil Online Now",
            ],
            descriptions: [
              "Topsoil from $24 per cu. yard. Skip bags - bulk delivery is faster, cheaper, and easier.",
              "Real yard, real inventory. Not a broker. Topsoil delivered across Suffolk County fast.",
              "Order today, delivered as soon as tomorrow. We dump exactly where you need it. No hassle.",
              "Screened topsoil for lawns, gardens, and grading. Use our calculator for exact yardage.",
            ],
            finalUrl: "/buy/topsoil",
            path1: "Topsoil",
            path2: "Delivery",
          },
        ],
      },
      {
        name: "Compost",
        keywords: [
          { text: "compost delivery near me", matchType: "EXACT" },
          { text: "bulk compost delivery", matchType: "EXACT" },
          { text: "premium compost per cubic yard", matchType: "EXACT" },
          { text: "organic compost for sale", matchType: "EXACT" },
          { text: "compost delivery long island", matchType: "PHRASE" },
          { text: "bulk compost near me", matchType: "PHRASE" },
          { text: "compost delivery suffolk", matchType: "PHRASE" },
          { text: "compost supplier suffolk county", matchType: "BROAD" },
        ],
        negativeKeywords: ["bin", "tumbler", "how to compost", "worms", "jobs", "free"],
        ads: [
          {
            headlines: [
              "Eastern Landscape Supply",
              "Organic Compost Delivery",
              "Compost From $32 Per Yard",
              "Suffolk County Delivery",
              "Order Compost Online",
              "Rich Organic Nutrients",
              "Fast Same-Day Delivery",
              "Locally Sourced Compost",
              "Gardens & Raised Beds",
              "Patchogue to Southampton",
              "Open 6 Days a Week",
              "Certified Organic Blend",
              "Bulk Pricing Per Cu. Yard",
              "Call Us Today",
              "Get a Delivery Estimate",
            ],
            descriptions: [
              "Certified organic compost from $32 per cu. yard. Nutrient-rich blend for gardens and lawns.",
              "Locally sourced compost delivered from our Center Moriches yard. Perfect for spring planting.",
              "Boost your soil with premium organic compost. Bulk delivery across Suffolk County.",
              "Order compost online for fast delivery. Not a middleman - direct from our supply yard.",
            ],
            finalUrl: "/buy/topsoil",
            path1: "Compost",
            path2: "Organic",
          },
        ],
      },
      {
        name: "Fill Dirt",
        keywords: [
          { text: "fill dirt delivery near me", matchType: "EXACT" },
          { text: "clean fill dirt for sale", matchType: "EXACT" },
          { text: "fill dirt suffolk county", matchType: "EXACT" },
          { text: "fill dirt delivery cost", matchType: "EXACT" },
          { text: "fill dirt delivery long island", matchType: "PHRASE" },
          { text: "bulk fill dirt near me", matchType: "PHRASE" },
          { text: "fill dirt per cubic yard", matchType: "PHRASE" },
          { text: "fill dirt supplier suffolk county", matchType: "BROAD" },
        ],
        negativeKeywords: ["free fill dirt", "contaminated", "hazardous", "jobs", "free"],
        ads: [
          {
            headlines: [
              "Eastern Landscape Supply",
              "Clean Fill Dirt Delivery",
              "Fill Dirt From $15 Per Yd",
              "Suffolk County Delivery",
              "Order Fill Dirt Online",
              "Estimate How Much You Need",
              "Fast Same-Day Delivery",
              "Fill Holes & Grade Lots",
              "Direct From Our Yard",
              "Patchogue to Southampton",
              "Open 6 Days a Week",
              "Pool Fill & Grading",
              "Bulk Pricing Per Cu. Yard",
              "Call Us Today",
              "Get a Delivery Estimate",
            ],
            descriptions: [
              "Clean fill dirt from $15 per cu. yard. Use our estimator to calculate what you need.",
              "Fill holes, grade properties, and prep foundations. Fast bulk delivery across Suffolk.",
              "Fill dirt delivered direct from our Center Moriches yard. Competitive bulk pricing.",
              "Need fill dirt? Order online and get fast delivery to your Suffolk County site.",
            ],
            finalUrl: "/buy/fill-dirt",
            path1: "Fill-Dirt",
            path2: "Delivery",
          },
        ],
      },
    ],
    sitelinks: [
      { linkText: "Order Topsoil Online", description1: "Screened organic from $24/yd", description2: "Bulk delivery available", finalUrl: "/buy/topsoil" },
      { linkText: "Fill Dirt Estimator", description1: "Calculate how much you need", description2: "Fast local delivery", finalUrl: "/buy/fill-dirt" },
      { linkText: "Delivery Calculator", description1: "Free estimates for delivery", description2: "Suffolk County coverage", finalUrl: "/calculator" },
      { linkText: "View All Materials", description1: "Browse our full catalog", description2: "Mulch, stone, gravel, sand", finalUrl: "/shop" },
    ],
    callouts: [
      { text: "Free Delivery Estimates" },
      { text: "Locally Sourced Topsoil" },
      { text: "Same-Day Delivery" },
      { text: "Bulk Pricing Available" },
      { text: "Open Mon-Sat" },
      { text: "Direct From Our Yard" },
    ],
  },

  // ═══ Campaign 2: Mulch Delivery (Tier 1) ═══
  {
    campaignName: "ELM - Mulch Delivery - Spring 2026",
    dailyBudgetCents: 1800,
    biddingStrategy: "MAXIMIZE_CLICKS",
    geoTargets: GEO_TARGETS,
    landingPageUrl: "/buy/mulch",
    adGroups: [
      {
        name: "Mulch Delivery General",
        keywords: [
          { text: "mulch delivery near me", matchType: "EXACT" },
          { text: "buy mulch in bulk", matchType: "EXACT" },
          { text: "mulch delivery suffolk county", matchType: "EXACT" },
          { text: "bulk mulch for sale", matchType: "EXACT" },
          { text: "mulch delivery cost", matchType: "EXACT" },
          { text: "mulch delivery price", matchType: "EXACT" },
          { text: "mulch delivery long island", matchType: "PHRASE" },
          { text: "mulch per cubic yard", matchType: "PHRASE" },
          { text: "double ground mulch near me", matchType: "PHRASE" },
          { text: "mulch yard near me", matchType: "PHRASE" },
          { text: "same day mulch delivery", matchType: "PHRASE" },
          { text: "mulch delivery near me", matchType: "PHRASE" },
          { text: "mulch delivery patchogue", matchType: "PHRASE" },
          { text: "mulch delivery riverhead", matchType: "PHRASE" },
          { text: "mulch delivery hampton bays", matchType: "PHRASE" },
          { text: "mulch supplier suffolk county", matchType: "BROAD" },
          { text: "bulk mulch yard long island", matchType: "BROAD" },
        ],
        negativeKeywords: ["rubber", "pine needles", "leaves", "how to", "jobs", "hiring", "free", "home depot", "lowes", "bagged", "craigslist"],
        ads: [
          {
            headlines: [
              "Eastern Landscape Supply",
              "Mulch Delivered Tomorrow",
              "Mulch From $20 Per Yard",
              "Skip Bagged Mulch - Bulk",
              "5 Mulch Colors In Stock",
              "Same-Day Mulch Delivery",
              "Double Ground Mulch",
              "Dumped Where You Need It",
              "Order Mulch Online Today",
              "Black Mulch From $30/Yard",
              "Red Mulch From $38/Yard",
              "Save vs Bagged Mulch",
              "Processed Locally",
              "Call Us Today",
              "Real Yard, Not a Broker",
            ],
            descriptions: [
              "Bulk mulch from $20 per cu. yard. Skip bags - save time, money, and multiple store trips.",
              "5 colors in stock. Double ground mulch delivered fast across Suffolk County.",
              "Processed locally, delivered from our yard. Not a broker - real inventory ready now.",
              "Order today for fast delivery. We dump mulch exactly where you need it. No hassle.",
            ],
            finalUrl: "/buy/mulch",
            path1: "Mulch",
            path2: "Delivery",
          },
        ],
      },
      {
        name: "Mulch by Color",
        keywords: [
          { text: "black mulch delivery", matchType: "EXACT" },
          { text: "brown mulch delivery", matchType: "EXACT" },
          { text: "red mulch delivery near me", matchType: "EXACT" },
          { text: "black mulch per cubic yard", matchType: "EXACT" },
          { text: "red mulch price per yard", matchType: "EXACT" },
          { text: "brown mulch bulk delivery", matchType: "PHRASE" },
          { text: "red mulch near me", matchType: "PHRASE" },
          { text: "natural mulch delivery", matchType: "PHRASE" },
          { text: "chocolate mulch near me", matchType: "PHRASE" },
        ],
        negativeKeywords: ["rubber", "jobs", "free"],
        ads: [
          {
            headlines: [
              "Eastern Landscape Supply",
              "Black Mulch From $30/Yard",
              "Brown Mulch Delivery",
              "Red Mulch From $38/Yard",
              "5 Colors Available Now",
              "Double Ground Premium",
              "Choose Your Mulch Color",
              "Fast Suffolk Delivery",
              "Processed Locally",
              "Bulk Mulch In Stock",
              "Natural Mulch From $20",
              "Open 6 Days a Week",
              "Order Online Today",
              "Call Us Today",
              "Get a Delivery Estimate",
            ],
            descriptions: [
              "Pick your color: brown, black, red, natural, or chocolate. Double ground, per cu. yard.",
              "Processed locally, delivered fast from our Center Moriches yard. Bulk across Suffolk.",
              "Refresh beds and borders with fresh double ground mulch. Skip bags - bulk saves money.",
              "Red mulch from $38, black and brown from $30, natural from $20 per cu. yard. Order now.",
            ],
            finalUrl: "/buy/mulch",
            path1: "Mulch",
            path2: "Colors",
          },
        ],
      },
    ],
    sitelinks: [
      { linkText: "Shop All Mulch Colors", description1: "Brown, black, red, natural", description2: "Double ground premium", finalUrl: "/buy/mulch" },
      { linkText: "Topsoil & Compost", description1: "Screened organic from $24/yd", description2: "Bulk delivery available", finalUrl: "/buy/topsoil" },
      { linkText: "Delivery Calculator", description1: "Free estimates for delivery", description2: "Suffolk County coverage", finalUrl: "/calculator" },
      { linkText: "Landscaping Services", description1: "Full service installations", description2: "Free quotes available", finalUrl: "/services/landscaping" },
    ],
    callouts: [
      { text: "Double Ground Mulch" },
      { text: "Multiple Colors" },
      { text: "Processed Locally" },
      { text: "Bulk Per Cu. Yard Pricing" },
      { text: "Same-Day Delivery" },
      { text: "We Install Too" },
    ],
  },

  // ═══ Campaign 3: Gravel & Stone (Tier 1) ═══
  {
    campaignName: "ELM - Gravel & Stone - Spring 2026",
    dailyBudgetCents: 1600,
    biddingStrategy: "MAXIMIZE_CLICKS",
    geoTargets: GEO_TARGETS,
    landingPageUrl: "/buy/pea-gravel",
    adGroups: [
      {
        name: "Pea Gravel",
        keywords: [
          { text: "pea gravel delivery near me", matchType: "EXACT" },
          { text: "pea gravel per cubic yard", matchType: "EXACT" },
          { text: "buy pea gravel in bulk", matchType: "EXACT" },
          { text: "pea gravel suffolk county", matchType: "EXACT" },
          { text: "pea gravel delivery price", matchType: "EXACT" },
          { text: "pea gravel delivery long island", matchType: "PHRASE" },
          { text: "pea gravel for patio", matchType: "PHRASE" },
          { text: "bulk pea gravel near me", matchType: "PHRASE" },
          { text: "pea gravel supplier suffolk", matchType: "BROAD" },
        ],
        negativeKeywords: ["aquarium", "fish tank", "jobs", "free", "home depot", "lowes", "bagged"],
        ads: [
          {
            headlines: [
              "Eastern Landscape Supply",
              "Pea Gravel Delivery",
              "Pea Gravel $82 Per Yard",
              "Suffolk County Delivery",
              "Order Pea Gravel Online",
              "Perfect for Patios",
              "Fast Same-Day Delivery",
              "LI Gravel, Local Yard",
              "Walkways & Garden Paths",
              "Patchogue to Southampton",
              "Open 6 Days a Week",
              "Drainage & Landscaping",
              "Multiple Sizes Available",
              "Call Us Today",
              "Get a Delivery Estimate",
            ],
            descriptions: [
              "Bulk pea gravel at $82 per cu. yard for patios, walkways, and drainage. Suffolk delivery.",
              "Long Island gravel delivered from our Center Moriches yard. Not a broker - real inventory.",
              "Perfect for garden paths, around fire pits, and between stepping stones. Order online.",
              "Need pea gravel? Calculate how much you need online and get fast delivery to your site.",
            ],
            finalUrl: "/buy/pea-gravel",
            path1: "Pea-Gravel",
            path2: "Bulk",
          },
        ],
      },
      {
        name: "Bluestone & Crushed Stone",
        keywords: [
          { text: "bluestone gravel delivery", matchType: "EXACT" },
          { text: "crushed bluestone near me", matchType: "EXACT" },
          { text: "bluestone gravel per yard", matchType: "EXACT" },
          { text: "crushed stone delivery price", matchType: "EXACT" },
          { text: "bluestone gravel delivery long island", matchType: "PHRASE" },
          { text: "crushed stone delivery suffolk", matchType: "PHRASE" },
          { text: "3/4 crushed stone delivery", matchType: "PHRASE" },
          { text: "crushed bluestone suffolk county", matchType: "BROAD" },
        ],
        negativeKeywords: ["jobs", "free", "home depot", "bagged"],
        ads: [
          {
            headlines: [
              "Eastern Landscape Supply",
              "Bluestone Gravel Delivery",
              "Crushed Stone $90 Per Yd",
              "Suffolk County Delivery",
              "Order Bluestone Online",
              "Driveways & Walkways",
              "Fast Same-Day Delivery",
              "3/4\" and 3/8\" In Stock",
              "Multiple Sizes Available",
              "Patchogue to Southampton",
              "Open 6 Days a Week",
              "Great for Driveways",
              "Direct From Our Yard",
              "Call Us Today",
              "Get a Delivery Estimate",
            ],
            descriptions: [
              "Crushed bluestone gravel at $90 per cu. yard. Great for driveways and walkways.",
              "Bluestone delivered from our Center Moriches yard. 3/4 and 3/8 inch sizes in stock.",
              "Upgrade your driveway with crushed bluestone. Order online, same-day delivery available.",
              "Suffolk County stone delivery. Competitive pricing, real inventory, not a middleman.",
            ],
            finalUrl: "/buy/bluestone-gravel",
            path1: "Bluestone",
            path2: "Delivery",
          },
        ],
      },
      {
        name: "RCA Crusher Run Base",
        keywords: [
          { text: "rca delivery near me", matchType: "EXACT" },
          { text: "crusher run delivery", matchType: "EXACT" },
          { text: "recycled concrete aggregate", matchType: "EXACT" },
          { text: "rca base material", matchType: "EXACT" },
          { text: "rca delivery price", matchType: "EXACT" },
          { text: "crusher run delivery long island", matchType: "PHRASE" },
          { text: "rca gravel for driveway", matchType: "PHRASE" },
          { text: "base material delivery suffolk", matchType: "PHRASE" },
          { text: "rca aggregate suffolk county", matchType: "BROAD" },
        ],
        negativeKeywords: ["jobs", "free", "rental", "disposal"],
        ads: [
          {
            headlines: [
              "Eastern Landscape Supply",
              "RCA & Crusher Run",
              "RCA Base From $20 Per Yd",
              "Suffolk County Delivery",
              "Fix Potholes & Driveways",
              "Shed & Patio Base",
              "Fast Same-Day Delivery",
              "Compacts Solid & Drains",
              "State Grade RCA $27/Yard",
              "Patchogue to Southampton",
              "Open 6 Days a Week",
              "Bulk Pricing Per Cu. Yard",
              "Direct From Our Yard",
              "Call Us Today",
              "Get a Delivery Estimate",
            ],
            descriptions: [
              "RCA from $20 per cu. yard. Crusher run for driveways, shed bases, and grading.",
              "Recycled concrete aggregate delivered fast. Fix potholes and build solid foundations.",
              "Base material delivered from our Center Moriches yard. Fast Suffolk County delivery.",
              "Need a solid base? RCA for driveways, patios, and shed foundations. Order online.",
            ],
            finalUrl: "/buy/rca-base",
            path1: "RCA-Base",
            path2: "Delivery",
          },
        ],
      },
      {
        name: "River Rock & Decorative Stone",
        keywords: [
          { text: "river rock delivery near me", matchType: "EXACT" },
          { text: "pocono river rock delivery", matchType: "EXACT" },
          { text: "decorative stone delivery", matchType: "EXACT" },
          { text: "whitestone gravel delivery", matchType: "EXACT" },
          { text: "landscape stone near me", matchType: "EXACT" },
          { text: "river rock per cubic yard", matchType: "PHRASE" },
          { text: "decorative gravel long island", matchType: "PHRASE" },
          { text: "whitestone delivery suffolk", matchType: "PHRASE" },
          { text: "decorative stone suffolk county", matchType: "BROAD" },
        ],
        negativeKeywords: ["jobs", "free", "images", "pictures"],
        ads: [
          {
            headlines: [
              "Eastern Landscape Supply",
              "Pocono River Rock",
              "Decorative Stone Delivery",
              "Suffolk County Delivery",
              "Whitestone From $135/Yard",
              "River Rock From $135/Yd",
              "Burgundy Red Stone $110",
              "Fast Same-Day Delivery",
              "Multiple Sizes In Stock",
              "Patchogue to Southampton",
              "Open 6 Days a Week",
              "Premium Landscape Stone",
              "Direct From Our Yard",
              "Call Us Today",
              "Get a Delivery Estimate",
            ],
            descriptions: [
              "Pocono river rock, whitestone, and burgundy red stone. Delivered per cu. yard.",
              "Premium decorative stone for landscaping. Multiple sizes at our Center Moriches yard.",
              "Transform your landscape with river rock or whitestone. Bulk delivery, great pricing.",
              "Decorative stone delivered to your project site. Order online or call for availability.",
            ],
            finalUrl: "/shop",
            path1: "Stone",
            path2: "Decorative",
          },
        ],
      },
    ],
    sitelinks: [
      { linkText: "Pea Gravel", description1: "Popular for patios and paths", description2: "From $82 per cu. yard", finalUrl: "/buy/pea-gravel" },
      { linkText: "Bluestone Gravel", description1: "Crushed bluestone gravel", description2: "Great for driveways", finalUrl: "/buy/bluestone-gravel" },
      { linkText: "RCA Crusher Run", description1: "Base material from $20/yard", description2: "Shed bases and driveways", finalUrl: "/buy/rca-base" },
      { linkText: "Boulders & Fieldstone", description1: "Decorative landscape stone", description2: "Multiple sizes in stock", finalUrl: "/buy/boulders" },
    ],
    callouts: [
      { text: "Gravel From $82 Per Yard" },
      { text: "Same-Day Available" },
      { text: "Multiple Sizes In Stock" },
      { text: "Driveway Experts" },
      { text: "Free Delivery Estimates" },
      { text: "Direct From Our Yard" },
    ],
  },

  // ═══ Campaign 4: Sand Delivery (Tier 2) ═══
  {
    campaignName: "ELM - Sand Delivery - Spring 2026",
    dailyBudgetCents: 600,
    biddingStrategy: "MAXIMIZE_CLICKS",
    geoTargets: GEO_TARGETS,
    landingPageUrl: "/buy/sand",
    adGroups: [
      {
        name: "Sand General",
        keywords: [
          { text: "sand delivery near me", matchType: "EXACT" },
          { text: "bulk sand delivery", matchType: "EXACT" },
          { text: "sand delivery suffolk county", matchType: "EXACT" },
          { text: "buy sand per cubic yard", matchType: "EXACT" },
          { text: "sand delivery cost", matchType: "EXACT" },
          { text: "sand delivery long island", matchType: "PHRASE" },
          { text: "bulk sand near me", matchType: "PHRASE" },
          { text: "sand yard near me", matchType: "PHRASE" },
          { text: "same day sand delivery", matchType: "PHRASE" },
          { text: "sand supplier suffolk county", matchType: "BROAD" },
        ],
        negativeKeywords: ["sandbox kit", "kinetic", "jobs", "free", "home depot", "bagged"],
        ads: [
          {
            headlines: [
              "Eastern Landscape Supply",
              "Bulk Sand Delivery",
              "Sand From $60 Per Yard",
              "Suffolk County Delivery",
              "5 Sand Types In Stock",
              "Mason & Concrete Sand",
              "Pool Sand Available",
              "Fast Same-Day Delivery",
              "Locally Sourced Sand",
              "Choose Sand by Project",
              "Patchogue to Southampton",
              "Open 6 Days a Week",
              "Direct From Our Yard",
              "Call Us Today",
              "Get a Delivery Estimate",
            ],
            descriptions: [
              "Mason, concrete, pool, and fine sand from $60 per cu. yard. Fast Suffolk delivery.",
              "Choose the right sand for your project. Delivered from our Center Moriches supply yard.",
              "Locally sourced sand for every application. Same-day delivery, competitive bulk pricing.",
              "Building or landscaping? We have the right sand. Not a broker - real stock on hand.",
            ],
            finalUrl: "/buy/sand",
            path1: "Sand",
            path2: "Delivery",
          },
        ],
      },
      {
        name: "Mason & Concrete Sand",
        keywords: [
          { text: "mason sand delivery", matchType: "EXACT" },
          { text: "concrete sand near me", matchType: "EXACT" },
          { text: "mason sand per cubic yard", matchType: "EXACT" },
          { text: "mason sand price", matchType: "EXACT" },
          { text: "mason sand delivery long island", matchType: "PHRASE" },
          { text: "concrete sand bulk delivery", matchType: "PHRASE" },
          { text: "washed sand for masonry", matchType: "PHRASE" },
          { text: "mason sand suffolk county", matchType: "BROAD" },
        ],
        negativeKeywords: ["jobs", "free"],
        ads: [
          {
            headlines: [
              "Eastern Landscape Supply",
              "Mason Sand $60 Per Yard",
              "Concrete Sand In Stock",
              "Suffolk County Delivery",
              "Washed Mason Sand",
              "For Brick & Block Work",
              "Fast Contractor Delivery",
              "Locally Sourced Sand",
              "Concrete Mix Ready Sand",
              "Patchogue to Southampton",
              "Open 6 Days a Week",
              "Trusted by Local Masons",
              "Direct From Our Yard",
              "Call Us Today",
              "Get a Delivery Estimate",
            ],
            descriptions: [
              "Washed mason and concrete sand at $60 per cu. yard. Bulk delivery for construction.",
              "Trusted by Suffolk County contractors. Fast delivery of mason sand to your site.",
              "Locally sourced sand from our Center Moriches yard. Perfect for brick and mortar.",
              "Need sand for a pour or masonry project? $60 per cu. yard with fast local delivery.",
            ],
            finalUrl: "/buy/sand",
            path1: "Mason-Sand",
            path2: "Bulk",
          },
        ],
      },
    ],
    sitelinks: [
      { linkText: "All Sand Types", description1: "Mason, concrete, pool, play", description2: "Choose the right sand", finalUrl: "/buy/sand" },
      { linkText: "Topsoil & Compost", description1: "Screened organic from $24/yd", description2: "Bulk delivery available", finalUrl: "/buy/topsoil" },
      { linkText: "Material Calculator", description1: "Estimate what you need", description2: "Free online tool", finalUrl: "/calculator" },
      { linkText: "Masonry Services", description1: "Professional installation", description2: "Free quotes available", finalUrl: "/services/masonry" },
    ],
    callouts: [
      { text: "Mason Sand $60 Per Yard" },
      { text: "Concrete Sand In Stock" },
      { text: "Pool Sand Available" },
      { text: "Locally Sourced Sand" },
      { text: "Same-Day Available" },
      { text: "Direct From Our Yard" },
    ],
  },

  // ═══ Campaign 5: Hardscape & Services (Tier 3) ═══
  {
    campaignName: "ELM - Hardscape & Services - Spring 2026",
    dailyBudgetCents: 300,
    biddingStrategy: "MAXIMIZE_CLICKS",
    geoTargets: GEO_TARGETS,
    landingPageUrl: "/buy/walkways",
    adGroups: [
      {
        name: "Walkway Materials & Install",
        keywords: [
          { text: "walkway materials near me", matchType: "EXACT" },
          { text: "flagstone walkway install", matchType: "EXACT" },
          { text: "walkway pavers delivery", matchType: "EXACT" },
          { text: "new walkway installation", matchType: "EXACT" },
          { text: "walkway materials long island", matchType: "PHRASE" },
          { text: "flagstone delivery suffolk", matchType: "PHRASE" },
          { text: "walkway gravel near me", matchType: "PHRASE" },
          { text: "stone walkway installation", matchType: "PHRASE" },
          { text: "walkway install suffolk county", matchType: "BROAD" },
          { text: "flagstone patio materials", matchType: "BROAD" },
        ],
        negativeKeywords: ["concrete walkway", "paver sealing", "jobs", "free"],
        ads: [
          {
            headlines: [
              "Eastern Landscape Supply",
              "Walkway Materials & More",
              "Flagstone Walkways",
              "Suffolk County Delivery",
              "Materials or Full Install",
              "Revamp Your Walkway",
              "Gravel & Stone Edging",
              "Free Project Quotes",
              "Not a Broker, Real Yard",
              "Patchogue to Southampton",
              "Open 6 Days a Week",
              "We Supply and Install",
              "Bluestone & Flagstone",
              "Call Us Today",
              "Get a Delivery Estimate",
            ],
            descriptions: [
              "Flagstone, bluestone, and gravel for walkways. Buy materials or get an install quote.",
              "Revamp or build a new walkway. We supply the stone and offer professional install.",
              "Walkway materials from our Center Moriches yard. Fast delivery across Suffolk County.",
              "From materials to finished walkway. Get a free quote for professional installation.",
            ],
            finalUrl: "/buy/walkways",
            path1: "Walkways",
            path2: "Materials",
          },
        ],
      },
      {
        name: "Fire Pits & Boulders",
        keywords: [
          { text: "fire pit materials near me", matchType: "EXACT" },
          { text: "natural stone fire pit", matchType: "EXACT" },
          { text: "boulders for landscaping", matchType: "EXACT" },
          { text: "fire pit installation", matchType: "EXACT" },
          { text: "fire pit stone delivery", matchType: "PHRASE" },
          { text: "landscape boulders near me", matchType: "PHRASE" },
          { text: "boulder delivery long island", matchType: "PHRASE" },
          { text: "fire pit build suffolk", matchType: "PHRASE" },
          { text: "fire pit installation suffolk", matchType: "BROAD" },
          { text: "decorative boulders long island", matchType: "BROAD" },
        ],
        negativeKeywords: ["gas fire pit", "propane", "portable", "jobs", "free"],
        ads: [
          {
            headlines: [
              "Eastern Landscape Supply",
              "Natural Fire Pit Stone",
              "Boulders & Fieldstone",
              "Suffolk County Delivery",
              "Fire Pit Materials",
              "We Build Fire Pits Too",
              "Free Project Quotes",
              "Landscape Boulders",
              "Materials or Full Install",
              "Patchogue to Southampton",
              "Open 6 Days a Week",
              "Multiple Sizes In Stock",
              "Direct From Our Yard",
              "Call Us Today",
              "Get a Delivery Estimate",
            ],
            descriptions: [
              "Natural stone and boulders for fire pits and landscaping. Materials or full install.",
              "Build a backyard fire pit with natural stone. Professional installation available.",
              "Landscape boulders, fieldstone, and fire pit kits. Delivered across Suffolk County.",
              "Create the perfect outdoor spot. Materials and expert installation from one supplier.",
            ],
            finalUrl: "/buy/firepits",
            path1: "Fire-Pits",
            path2: "Stone",
          },
        ],
      },
      {
        name: "Driveway Services & Materials",
        keywords: [
          { text: "gravel driveway repair", matchType: "EXACT" },
          { text: "gravel driveway installation", matchType: "EXACT" },
          { text: "driveway repair near me", matchType: "EXACT" },
          { text: "fix gravel driveway", matchType: "EXACT" },
          { text: "driveway gravel delivery", matchType: "EXACT" },
          { text: "driveway repair suffolk county", matchType: "PHRASE" },
          { text: "gravel driveway near me", matchType: "PHRASE" },
          { text: "driveway repair long island", matchType: "PHRASE" },
          { text: "crusher run for driveway", matchType: "PHRASE" },
          { text: "gravel driveway suffolk county", matchType: "BROAD" },
          { text: "driveway repair long island", matchType: "BROAD" },
        ],
        negativeKeywords: ["asphalt", "concrete driveway", "paving", "sealing", "jobs"],
        ads: [
          {
            headlines: [
              "Eastern Landscape Supply",
              "Gravel Driveway Experts",
              "Driveway Repair Service",
              "Suffolk County Service",
              "RCA & Crusher Run",
              "Materials or Full Install",
              "Fast Same-Day Delivery",
              "Fill Potholes Fast",
              "Free Driveway Quotes",
              "Patchogue to Southampton",
              "Open 6 Days a Week",
              "RCA Base From $20 Per Yd",
              "We Supply and Install",
              "Call Us Today",
              "Get a Delivery Estimate",
            ],
            descriptions: [
              "Gravel driveway repair and installation. Buy materials or get a free service quote.",
              "Fix potholes fast. RCA from $20 per cu. yard or full professional installation.",
              "Suffolk County driveway experts. Materials delivered or installed by our crew.",
              "Need a driveway fix? Get a free quote or order RCA and crusher run for delivery.",
            ],
            finalUrl: "/services/driveways",
            path1: "Driveway",
            path2: "Service",
          },
        ],
      },
    ],
    sitelinks: [
      { linkText: "Walkway Materials", description1: "Flagstone, gravel, edging", description2: "Build or revamp walkways", finalUrl: "/buy/walkways" },
      { linkText: "Fire Pit Kits", description1: "Natural stone fire pits", description2: "Boulders and flagstone", finalUrl: "/buy/firepits" },
      { linkText: "Driveway Services", description1: "Gravel driveway installs", description2: "Free quotes available", finalUrl: "/services/driveways" },
      { linkText: "View All Materials", description1: "Full landscape supply yard", description2: "Mulch, stone, topsoil", finalUrl: "/shop" },
    ],
    callouts: [
      { text: "Free Project Quotes" },
      { text: "Professional Install" },
      { text: "Materials & Labor" },
      { text: "Suffolk County Experts" },
      { text: "Licensed & Insured" },
      { text: "Direct From Our Yard" },
    ],
  },

  // ═══ Campaign 6: Contractor & Yard Search (Tier 2) ═══
  {
    campaignName: "ELM - Contractor & Yard Search - Spring 2026",
    dailyBudgetCents: 500,
    biddingStrategy: "MAXIMIZE_CLICKS",
    geoTargets: GEO_TARGETS,
    landingPageUrl: "/shop",
    adGroups: [
      {
        name: "Landscape Supply Yard",
        keywords: [
          { text: "landscape supply near me", matchType: "EXACT" },
          { text: "landscape supply yard", matchType: "EXACT" },
          { text: "bulk landscape materials", matchType: "EXACT" },
          { text: "landscape material delivery", matchType: "EXACT" },
          { text: "landscape supply suffolk county", matchType: "EXACT" },
          { text: "landscape supply long island", matchType: "PHRASE" },
          { text: "bulk material supplier near me", matchType: "PHRASE" },
          { text: "landscape yard near me", matchType: "PHRASE" },
          { text: "landscape supply open now", matchType: "PHRASE" },
          { text: "landscape material delivery suffolk", matchType: "BROAD" },
        ],
        negativeKeywords: ["design software", "landscape architect", "landscape design course", "jobs", "hiring", "free"],
        ads: [
          {
            headlines: [
              "Eastern Landscape Supply",
              "Real Yard. Real Trucks.",
              "Bulk Materials In Stock",
              "Suffolk County Yard",
              "Delivered Tomorrow",
              "Not a Middleman",
              "Same-Day Dump Delivery",
              "Mulch, Soil, Gravel, Sand",
              "Dumped Where You Need It",
              "Patchogue to Southampton",
              "Open Mon-Sat",
              "Contractor Friendly Yard",
              "Skip the Big Box Store",
              "Call Us Today",
              "We Supply and Install",
            ],
            descriptions: [
              "Real yard, real trucks, real inventory. Bulk mulch, topsoil, gravel, sand - fast.",
              "Not a broker. Direct from our Center Moriches yard. Same-day dump delivery Suffolk.",
              "Skip the store trips. Bulk materials dumped where you need them. Contractor pricing.",
              "Mulch from $20, topsoil from $24, RCA from $20 per cu. yard. Order online today.",
            ],
            finalUrl: "/shop",
            path1: "Supply-Yard",
            path2: "Suffolk",
          },
        ],
      },
      {
        name: "Masonry Supply",
        keywords: [
          { text: "masonry supply near me", matchType: "EXACT" },
          { text: "masonry materials delivery", matchType: "EXACT" },
          { text: "mason supply yard", matchType: "EXACT" },
          { text: "masonry supply suffolk county", matchType: "EXACT" },
          { text: "masonry supply long island", matchType: "PHRASE" },
          { text: "mason sand and stone delivery", matchType: "PHRASE" },
          { text: "masonry materials near me", matchType: "PHRASE" },
          { text: "masonry supplier suffolk county", matchType: "BROAD" },
        ],
        negativeKeywords: ["jobs", "hiring", "free"],
        ads: [
          {
            headlines: [
              "Eastern Landscape & Mason",
              "Masonry Supply Yard",
              "Mason Sand $60 Per Yard",
              "Suffolk County Yard",
              "Stone, Sand & Gravel",
              "Not a Middleman",
              "Same-Day Dump Delivery",
              "Bluestone, Flagstone",
              "Dumped at Your Job Site",
              "Patchogue to Southampton",
              "Open Mon-Sat",
              "Trusted by Local Masons",
              "Real Yard. Real Trucks.",
              "Call Us Today",
              "Concrete Sand In Stock",
            ],
            descriptions: [
              "Mason sand, concrete sand, bluestone, and flagstone. Delivered to your site same-day.",
              "Real masonry supply yard in Center Moriches. Not a broker - come see our stock.",
              "Trusted by Suffolk County masons. Bulk pricing per cu. yard with fast dump delivery.",
              "Everything for your masonry project. Sand from $60, bluestone from $90 per cu. yard.",
            ],
            finalUrl: "/shop",
            path1: "Masonry",
            path2: "Supply",
          },
        ],
      },
      {
        name: "Contractor Material Delivery",
        keywords: [
          { text: "contractor material delivery", matchType: "EXACT" },
          { text: "bulk material delivery near me", matchType: "EXACT" },
          { text: "dump truck delivery near me", matchType: "EXACT" },
          { text: "bulk gravel supplier", matchType: "EXACT" },
          { text: "construction material delivery", matchType: "EXACT" },
          { text: "contractor delivery suffolk", matchType: "PHRASE" },
          { text: "bulk delivery to job site", matchType: "PHRASE" },
          { text: "dump truck material delivery", matchType: "PHRASE" },
          { text: "same day material delivery", matchType: "PHRASE" },
          { text: "contractor material supplier long island", matchType: "BROAD" },
        ],
        negativeKeywords: ["lumber", "dumpster", "junk removal", "equipment", "jobs", "free"],
        ads: [
          {
            headlines: [
              "Eastern Landscape Supply",
              "Contractor Delivery",
              "Dumped Where You Need It",
              "Suffolk County Delivery",
              "Same-Day Dump Delivery",
              "Real Yard. Real Trucks.",
              "Delivered Tomorrow",
              "Not a Broker",
              "Bulk Job Site Delivery",
              "Patchogue to Southampton",
              "Open Mon-Sat 7AM",
              "Gravel, Sand, Topsoil",
              "Skip the Supply Run",
              "Call Us Today",
              "We Deliver All Day",
            ],
            descriptions: [
              "Bulk materials dumped where you need them. Real yard, real trucks, same-day Suffolk.",
              "Stop wasting time on supply runs. We deliver mulch, gravel, topsoil to your job site.",
              "Not a middleman. Direct from our Center Moriches yard. Contractor-friendly hours.",
              "Dump truck delivery of any material. Order online or call. Patchogue to Southampton.",
            ],
            finalUrl: "/shop",
            path1: "Contractor",
            path2: "Delivery",
          },
        ],
      },
    ],
    sitelinks: [
      { linkText: "Full Product Catalog", description1: "Mulch, topsoil, gravel, sand", description2: "All bulk materials", finalUrl: "/shop" },
      { linkText: "Driveway Services", description1: "Gravel driveway installs", description2: "Free quotes available", finalUrl: "/services/driveways" },
      { linkText: "Delivery Calculator", description1: "Free estimates for delivery", description2: "Suffolk County coverage", finalUrl: "/calculator" },
      { linkText: "Landscaping Services", description1: "Full service installations", description2: "Free quotes available", finalUrl: "/services/landscaping" },
    ],
    callouts: [
      { text: "Real Yard. Real Trucks." },
      { text: "Not a Middleman" },
      { text: "Same-Day Dump Delivery" },
      { text: "Contractor Friendly" },
      { text: "Open Mon-Sat 7AM" },
      { text: "Bulk Pricing Per Yard" },
    ],
  },
];

async function main() {
  console.log(`Pushing ${campaigns.length} campaigns to Google Ads...\n`);

  for (const campaign of campaigns) {
    try {
      console.log(`Pushing: ${campaign.campaignName}...`);
      console.log(`  Budget: $${(campaign.dailyBudgetCents / 100).toFixed(2)}/day`);
      console.log(`  Ad Groups: ${campaign.adGroups.length}`);
      console.log(`  Keywords: ${campaign.adGroups.reduce((s, ag) => s + ag.keywords.length, 0)}`);

      const result = await pushCampaignToGoogleAds(campaign);

      console.log(`  ✓ Campaign: ${result.campaignResourceName}`);
      console.log(`  ✓ Ad Groups: ${result.adGroupResourceNames.length}`);
      console.log(`  ✓ Ads: ${result.adResourceNames.length}`);
      console.log(`  ✓ Sitelinks: ${result.sitelinkCount}`);
      console.log(`  ✓ Callouts: ${result.calloutCount}`);
      console.log();
    } catch (err: any) {
      console.error(`  ✗ FAILED: ${campaign.campaignName}`);
      if (err?.errors) {
        for (const e of err.errors) {
          console.error(`    code: ${JSON.stringify(e.error_code)}`);
          console.error(`    msg: ${e.message}`);
          if (e.location) console.error(`    loc: ${JSON.stringify(e.location)}`);
          if (e.details) console.error(`    details: ${JSON.stringify(e.details)}`);
        }
      } else {
        console.error(`    Error: ${err?.message || JSON.stringify(err)}`);
      }
      console.log();
    }
  }

  console.log("Done!");
}

main().catch(console.error);
